[build]
  publish = "."

[[redirects]]
  from = "/impact"
  to = "/impact.html"
  status = 200

[[redirects]]
  from = "/writing"
  to = "/writing.html"
  status = 200

[[redirects]]
  from = "/values"
  to = "/values.html"
  status = 200

[[redirects]]
  from = "/now"
  to = "/now.html"
  status = 200

[[redirects]]
  from = "/impact.html"
  to = "/impact"
  status = 301

[[redirects]]
  from = "/writing.html"
  to = "/writing"
  status = 301

[[redirects]]
  from = "/values.html"
  to = "/values"
  status = 301

[[redirects]]
  from = "/now.html"
  to = "/now"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/experience"
  to = "/impact"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/writing"
  status = 301
